apiVersion: apps/v1C:\Users\Namit Pundir\source\repos\MenuItemListingWebApi\Controllers\
kind: Deployment
metadata:
  name: menuitemlistingwebapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MenuItemListingWebApi
  template:
    metadata:
      labels:
        app: MenuItemListingWebApi
    spec:
      containers:
      - name: menuitemlisting
        image: imgcontainer03.azurecr.io/menurepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: wallpapersn

---
apiVersion: v1
kind: Service
metadata:
  name: menuitemlistingwebapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MenuItemListingWebApi
